web/router.ex
defmodule Allbeerme.Router do
  use Allbeerme.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :admin do
    plug :put_layout, {Allbeerme.LayoutView, :admin}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Allbeerme do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/not_found", PageController, :not_found
    resources "/beers", BeerController, only: [:index, :show]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/admin", Allbeerme, as: :admin do
    pipe_through [:browser, :admin]

    get "/", Admin.BeerController, :index
    resources "/beers", Admin.BeerController
    resources "/images", Admin.ImageController
    resources "/users", Admin.UserController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Allbeerme do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Allbeerme.LayoutView do
  use Allbeerme.Web, :view

  def current_user(conn) do
    Plug.Conn.get_session(conn, :current_user)
  end

  def current_link(conn, title, path) do
    active = conn.request_path == path
    class = if active, do: "active", else: nil
    current = if active, do: content_tag(:span, "(current)", class: "sr-only"), else: nil

    ~E"""
      <li class="nav-item <%= class %>">
        <%= link to:  path, class: "nav-link" do %>
          <%= title %> <%= current %>
        <% end %>
      </li>
    """
  end

  defp render_flash(type, message) do
    ~E"""
    <div class="alert alert-<%= type %>" role="alert">
      <%= message %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    """
  end

  def show_flash(conn) do
    case get_flash(conn) do
      %{"info" => msg} ->
        render_flash("info", msg)
      %{"error" => msg} ->
        render_flash("danger", msg)
      _ ->
        ""
    end
  end
end

web/templates/layout/admin.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Sivard">

    <title>Информационный портал о пиве! - Админка</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/dist/app.css") %>">
  </head>

  <body>
    <div class="container">
      <nav class='navbar navbar-expand-lg navbar-dark bg-dark'>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%= link "Allbeerme", to: '/admin', class: 'navbar-brand' %>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <%= current_link(@conn, "Пиво", admin_beer_path(@conn, :index)) %>
            <%= current_link(@conn, "Пользователи", admin_user_path(@conn, :index)) %>
            <%= current_link(@conn, "Картинки", admin_image_path(@conn, :index)) %>
          </ul>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= if user = current_user(@conn) do %>
                <%= link to: session_path(@conn, :delete, user.id), method: :delete, title: "Выйти", class: 'nav-link' do %>
                  Выйти <i class="fa fa-sign-in" aria-hidden="true"></i>
                <% end %>
              <% else %>
                <%= link to: session_path(@conn, :new), title: "Войти", class: 'nav-link' do %>
                  Войти <i class="fa fa-sign-out" aria-hidden="true"></i>
                <% end %>
              <% end %>
            </li>
          </ul>
        </div>
      </nav>
      <%= show_flash(@conn) %>

      <main role="main">
        <div class="row">
          <div class="col-12">
            <%= if user = current_user(@conn) do %>
              <p class="text-right">Вы авторизованы как <span class='font-weight-bold'><%= user.username %></span></p>
            <% end %>
            <%= render @view_module, @view_template, assigns %>
          </div>
        </div>
      </main>

      <footer class='fixed-bottom'>
        <div class='container'>
          <div class='row'>
            <div class='col-12'>
              <div class='bg-dark text-white navbar'>
                Copyright © <%= Date.utc_today.year %> Sivard
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/dist/app.js") %>"></script>
  </body>
</html>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render_existing(@view_module, "meta." <> @view_template, assigns) ||
        render(Allbeerme.LayoutView, "meta.html", assigns) %>

    <link rel="stylesheet" href="<%= static_path(@conn, "/dist/app.css") %>">
    <meta name="yandex-verification" content="ba6813d6847eae2b" />
  </head>

  <body>
    <div class="container">
      <nav class='navbar navbar-expand-lg navbar-dark bg-dark'>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%= link "Allbeerme", to: '/', class: 'navbar-brand' %>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <%= current_link(@conn, "Марки пива", beer_path(@conn, :index)) %>
          </ul>
        </div>
      </nav>

      <%= show_flash(@conn) %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

      <footer class='fixed-bottom'>
        <div class='container'>
          <div class='row'>
            <div class='col-12'>
              <div class='bg-dark text-white navbar'>
                Copyright © <%= Date.utc_today.year %> Sivard
              </div>
            </div>
          </div>
        </div>
      </footer>
    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/dist/app.js") %>"></script>
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript" >
        (function (d, w, c) {
            (w[c] = w[c] || []).push(function() {
                try {
                    w.yaCounter47296188 = new Ya.Metrika({
                        id:47296188,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true,
                        webvisor:true
                    });
                } catch(e) { }
            });

            var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
            s.type = "text/javascript";
            s.async = true;
            s.src = "https://mc.yandex.ru/metrika/watch.js";

            if (w.opera == "[object Opera]") {
                d.addEventListener("DOMContentLoaded", f, false);
            } else { f(); }
        })(document, window, "yandex_metrika_callbacks");
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/47296188" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
  </body>
</html>

web/templates/layout/meta.html.eex
    <meta name="author" content="Sivard">
    <meta name="description" content="Информационный портал о пиве - здесь представлен полный список сортов пива.">
    <meta name="keywords" content="пиво, о пиве, сайт о пиве, все пиво мне">
    <title>Информационный портал о пиве.</title>